title: 'Pol Goasdoué, Interactions design'
description: Première tentative de génération d'un site statique.
github_repo: jekyll
github_username: jekyll
social_link: twitter
social_username: jekyllrb
theme_color: black
remote_theme: broccolini/swiss
